Acme\JobsBundle\Entity\Categories:
  type: entity
  table: categories
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
    slug:
      type: string
      length: 255
      fixed: false
      nullable: false
  oneToMany: 
    jobs:
      targetEntity: Jobs
      mappedBy: category  
  lifecycleCallbacks: {  }
  repositoryClass: Acme\JobsBundle\Entity\CategoriesRepository