AcmeTestBundle:
    resource: "@AcmeTestBundle/Resources/config/routing.yml"
    prefix:   /

JobsBundle:
    resource: "@JobsBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern:  /
    defaults: { _controller: JobsBundle:Jobs:index }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
